name: Publish on GitHub, Curseforge & Modrinth

on: [ pull_request, workflow_dispatch ]

env:
  JAVA_VERSION: 17
  MOD_VERSION: 1.0.0+1.20.2
  RELEASE_NAME: fossils-mod-1.0.0+1.20.2
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Curseforge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 933922
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: dZzqfl98
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "${{env.MOD_VERSION}}"
          github-prerelease: true
          github-token: "${{env.GITHUB_TOKEN}}"

          dependencies: |
            fabric-language-kotlin@1.10.13+kotlin.1.9.20(required){modrinth:Ha28R6CL}{curseforge:4833025}#(ignore:github)
            fabric-api@0.90.7+1.20.2(required){modrinth:P7dR8mSH}{curseforge:4834998}#(ignore:github)

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.MD

          java: "${{env.JAVA_VERSION}}"